let arr = [1, 2, 5, 6, 7];
arr[0] = 23;
console.log(arr);
console.log(typeof arr);
console.log(arr.length);
console.log(arr[3]);
console.log(arr[0]);
console.log(arr.toString());
console.log(arr.join(""));
arr.pop();
console.log(arr);
arr.push(100);
console.log(arr);
arr.push("sameer");
console.log(arr);
a = arr.shift();
console.log(arr);
console.log(a);
arr.unshift("reemas");
console.log(arr);
delete arr[3];
console.log(arr);
let arr2 = [8, 3, 4, 9, 10];
let arr3 = [9, 4, 5, 6];
a2 = arr.concat(arr2, arr3);
console.log(a2);
console.log(arr);
console.log(arr2);
console.log(arr3);
console.log(arr3.sort());
console.log(arr);
arr.splice(0, 3, 1, 2, 3, 4);
console.log(arr);